location ~* \.(html|css|js|jpg|jpeg|png|gif|webp|svg)$ {
  add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0" always;
  add_header Pragma "no-cache" always;
  add_header Expires "0" always;
  expires off;
  etag off;
}
